# coding: utf-8

"""
    SBC Pay API Reference

    BC Registries Pay API reference documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.payment_receipt_input import PaymentReceiptInput  # noqa: E501
from openapi_client.rest import ApiException

class TestPaymentReceiptInput(unittest.TestCase):
    """PaymentReceiptInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PaymentReceiptInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.payment_receipt_input.PaymentReceiptInput()  # noqa: E501
        if include_optional :
            return PaymentReceiptInput(
                corp_name = '0', 
                business_number = '0', 
                recognition_date_time = '0', 
                filing_identifier = '0', 
                filing_date_time = '0', 
                file_name = '0'
            )
        else :
            return PaymentReceiptInput(
        )

    def testPaymentReceiptInput(self):
        """Test PaymentReceiptInput"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
