# coding: utf-8

"""
    SBC Pay API Reference

    BC Registries Pay API reference documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InvoiceReference(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'invoice_number': 'str',
        'reference_number': 'str',
        'status_code': 'str'
    }

    attribute_map = {
        'id': 'id',
        'invoice_number': 'invoiceNumber',
        'reference_number': 'referenceNumber',
        'status_code': 'statusCode'
    }

    def __init__(self, id=None, invoice_number=None, reference_number=None, status_code=None, local_vars_configuration=None):  # noqa: E501
        """InvoiceReference - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._invoice_number = None
        self._reference_number = None
        self._status_code = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if invoice_number is not None:
            self.invoice_number = invoice_number
        if reference_number is not None:
            self.reference_number = reference_number
        if status_code is not None:
            self.status_code = status_code

    @property
    def id(self):
        """Gets the id of this InvoiceReference.  # noqa: E501


        :return: The id of this InvoiceReference.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InvoiceReference.


        :param id: The id of this InvoiceReference.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def invoice_number(self):
        """Gets the invoice_number of this InvoiceReference.  # noqa: E501


        :return: The invoice_number of this InvoiceReference.  # noqa: E501
        :rtype: str
        """
        return self._invoice_number

    @invoice_number.setter
    def invoice_number(self, invoice_number):
        """Sets the invoice_number of this InvoiceReference.


        :param invoice_number: The invoice_number of this InvoiceReference.  # noqa: E501
        :type invoice_number: str
        """

        self._invoice_number = invoice_number

    @property
    def reference_number(self):
        """Gets the reference_number of this InvoiceReference.  # noqa: E501


        :return: The reference_number of this InvoiceReference.  # noqa: E501
        :rtype: str
        """
        return self._reference_number

    @reference_number.setter
    def reference_number(self, reference_number):
        """Sets the reference_number of this InvoiceReference.


        :param reference_number: The reference_number of this InvoiceReference.  # noqa: E501
        :type reference_number: str
        """

        self._reference_number = reference_number

    @property
    def status_code(self):
        """Gets the status_code of this InvoiceReference.  # noqa: E501


        :return: The status_code of this InvoiceReference.  # noqa: E501
        :rtype: str
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this InvoiceReference.


        :param status_code: The status_code of this InvoiceReference.  # noqa: E501
        :type status_code: str
        """

        self._status_code = status_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvoiceReference):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InvoiceReference):
            return True

        return self.to_dict() != other.to_dict()
